### ISSUE TITLE
Improvements to TIMERS

### ISSUE THREAD

**Issue by MysticalOS** [BigWigsMods/Transcriptor#1]
There are some improvements to "TIMERS" I wanted to suggest
- [ ] Support for SPELL_AURA_APPLIED events if sourceGUID and destGUID can both be returned to a boss1-5 GUID. There are many times where bosses have important things they cast that simply don't have a SUCCESS or START event. Often times being channeled spells were boss gains and loses a buff instead.
- [ ] Scan for keywords in UNIT_ events that can mark phase changes and highlight this in TIMERS somehow. for example you can search for "form" or "phase" or "eject" or "permanent feign death" so if a boss cast "Phase 2 transition" transcriptor could identify this in timers in some way to acknowledge you may be looking for some kind of reset. So it might be like pull:7, 60 60, phase:15, 60 60 instead of 7, 60, 60, 71, 60. this of course may not be worth the hastle. doable but imperfect since many time phase transitions aren't as obvious as "phase" or "arachnid form".
- [ ] Alternate suggestion to 2 would be to simply add a new thing called "possible phases" and just dump any unit or spell_cast event there that contains key words. And this is probably more ideal. You can then add additional keywords for common phase change spells and just provide a list and nothing more.
  A few off top of head are
  "phase"
  "form"
  "feign death"
  "mode"
  "energize"
  "regen"
  "Suicide"
  "change"
  "model"

**Comment by funkydude** [comment]
Added support for SPELL_AURA_APPLIED minus the boss filtering. We could add that too if people want that.

The rest I'll leave as up for grabs for now.

**Comment by MysticalOS** [comment]
I see you started on this using boss mod stage messages.

FYI you can grab DBMS stage messages too

fireEvent("DBM_Announce", message, self.icon, self.type, self.spellId, self.mod.id)

type would be "stage" and spellId arg would be stage number in a stage message if you wanted to be even more specific

**Comment by funkydude** [comment]
https://github.com/BigWigsMods/Transcriptor/commit/48ded5fb6c5b5d04b6d64ed3dd608b89f680b582 closed this, maybe you missed it?

**Comment by MysticalOS** [comment]
Yeah I hadn't done that pull yet.

But I did see commit on grabbing stage messages from BW, and was just letting you know you could do same with DBM. Figured you were gonna use that to enhance this somehow by trusting mod when no hard coded stage information is known by transcriptor.
