### ISSUE TITLE
Still cases of not filtering players

### ISSUE THREAD

**Issue by MysticalOS** [BigWigsMods/Transcriptor#14]
### What steps will reproduce the problem?  
1.  Just attempt to log any world boss on a PVP realm
2.  
3.  

### What version of Transcriptor are you using?
7.3.1-2

### Do you have an error log of what happened?
No error, just a log that is full of player spells, and entire TIMERS section has more pvp data than boss data.

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)
I thought you already added a bit.band check for player unit to just filter all player events, but maybe you only did it in raids? World bosses matter too though and on PVP realms you get a lot of junk in your logs

**Comment by funkydude** [comment]
This will never be fixed until combat log flags themselves are fixed.
