### ISSUE TITLE
bad argument #4 to 'format' (string expected, got nil)

### ISSUE THREAD

**Issue by Causese** [BigWigsMods/Transcriptor#16]
![image](https://user-images.githubusercontent.com/16833/41469252-70e12f34-70a4-11e8-961e-9a3d7e7ec4f5.png)

**Comment by funkydude** [comment]
Needs more info.

**Comment by Causese** [comment]
oh boi. kinda hard to reproduce transcriptor errors on bosses with limited time testing
![image](https://user-images.githubusercontent.com/16833/42893242-b00ca226-8aab-11e8-9679-b7bf8342996a.png)


basically an ability from blightspreader tendril (g'huun, bfa endboss encounter)
can be interrupted else raidwide damage

not sure what kind of info you're looking for. feel free to close it

**Comment by funkydude** [comment]
Just leaving this open to see if it's reproducible on future boss attempts.

**Comment by funkydude** [comment]
Fixed by fe09d95d057c5c7b9f45cbb9d249e8839c4cc4ed
