### ISSUE TITLE
Filter "dummy nuke"

### ISSUE THREAD

**Issue by MysticalOS** [BigWigsMods/Transcriptor#2]
I can't tell you how many fights I saw a bunch of "Dummy Nuke" casts spammed in log.
I can tell you how many times they've been useful in boss mod creation though. 0.

Il'gynoth is one such example. Half the log is
"<0.27 18:28:21> [UNIT_SPELLCAST_SUCCEEDED] Il'gynoth(Lamerokk) [[boss2:Dummy Nuke::3-2084-1520-6363-141679-001182EA85:141679]]", -- [6]

I suggestion to make it an option is in the case that MAYBE one day, it's useful for something......One day......

**Comment by funkydude** [comment]
I agree these are useless but I'm hesitant to be overly aggressive with filtering.
