### ISSUE TITLE
Autolog?

### ISSUE THREAD

**Issue by redcatelf** [BigWigsMods/Transcriptor#26]
Would it be possible to automatically log all keystones and raid boss fights? Sometimes I notice some issue during a fight (or while watching a replay) and want to submit a transcriptor log with my issue report, but then it's already too late because I didn't activate it.

Or would that cause some ballooning memory usage issue?

**Comment by Justw8** [comment]
https://www.curseforge.com/wow/addons/bigwigs_transcriptor
Is this what you are looking for?

**Comment by redcatelf** [comment]
Oh beautiful, thank you!

**Comment by redcatelf** [comment]
Perhaps a link could be added to the Curseforge page? I'm assuming using Transcriptor with BigWigs is a fairly common use case.
