### ISSUE TITLE
Log GetInstanceInfo() results on ENCOUNTER_START/END

### ISSUE THREAD

**Issue by emmericp** [BigWigsMods/Transcriptor#45]
Difficulty info is currently only available via the log's name. This has some limits:

1) it may be outdated/incorrect if someone starts logging outside
2) sometimes you get people splitting the logs via some tools that don't include this information

I think having it logged on ENCOUNTER_START/END may be helpful.

DBM already adds this as a custom message on combat detection to Transcriptor logs but I think this should probably be a default feature

**Comment by funkydude** [comment]
The difficulty ID is already part of the payload though?

**Comment by emmericp** [comment]
Sorry, I didn't mean to say difficulty info, I meant instance info: instance type, name, maximum players and id (at least the ID i can also get from a GUID). It's just neat to have it all in one place, example of what it looks like with DBM:

```
"<60.35 20:56:34> [DBM_Debug] GetInstanceInfo() = Molten Core, raid, 226, 20 Player, 20, 0, false, 409, 20#3",
"<60.35 20:56:34> [DBM_Debug] DBM:GetCurrentInstanceDifficulty() = normal20, 20 Player(2) - , 226, 20, 2#3",
"<60.35 20:56:34> [ENCOUNTER_START] 666#Garr#226#20",
```

Just looks more complete and is useful if parsing it automatically
