### ISSUE TITLE
v7.2.1-5 Regression

### ISSUE THREAD

**Issue by MysticalOS** [BigWigsMods/Transcriptor#8]
1x Transcriptor\Transcriptor-v7.2.1-5-g0c1f2e1.lua:855: bad argument #2 to 'format' (number expected, got nil)
[C]: ?
Transcriptor\Transcriptor-v7.2.1-5-g0c1f2e1.lua:855: in function <Transcriptor\Transcriptor.lua:846>

Locals:
(*temporary) = "<%.2f %s> [IsEncounterInProgress()] false"
(*temporary) = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = "number expected, got nil"

Also line 850 and 861

**Comment by funkydude** [comment]
Fixed locally but not pushed yet due to other pending changes.
